
// This file has been generated by the GUI designer. Do not modify.
namespace Xavalon.XamlStyler.XamarinStudio.Gui
{
	public partial class OptionsWidget
	{
		private global::Gtk.Alignment alContainer;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.Table tblContainer;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Xavalon.XamlStyler.XamarinStudio.Gui.OptionsWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Xavalon.XamlStyler.XamarinStudio.Gui.OptionsWidget";
			// Container child Xavalon.XamlStyler.XamarinStudio.Gui.OptionsWidget.Gtk.Container+ContainerChild
			this.alContainer = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.alContainer.Name = "alContainer";
			// Container child alContainer.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.tblContainer = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.tblContainer.Name = "tblContainer";
			this.tblContainer.RowSpacing = ((uint)(6));
			this.tblContainer.ColumnSpacing = ((uint)(6));
			w1.Add(this.tblContainer);
			this.GtkScrolledWindow.Add(w1);
			this.alContainer.Add(this.GtkScrolledWindow);
			this.Add(this.alContainer);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
