# Build Rider plugin

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  xamlStylerVersion: 3.2003.9
  majorMinor: 2020.1
  patch: $[counter(format('{0:yyMM}', pipeline.startTime), 0)]
  pluginVersion: $(majorMinor).$(patch)-$(xamlStylerVersion)

name: $(majorMinor).$(patch)-$(xamlStylerVersion)

steps:
- task: Gradle@2
  displayName: Gradle build
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    options: '-PPluginVersion=$(pluginVersion)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'buildPlugin'

- task: PublishBuildArtifacts@1
  displayName: Artifacts
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)\s\output'
    ArtifactName: 'plugins'
    publishLocation: 'Container'